const DEV_SECRET = 'dev-secret';
const STATUS_OK = 200;
const CREATED = 201;
const INVAILD_ID = 'NotValidId';
const ERROR_CODE_UNIQUE = 11000;
const BAD_REQUEST_CODE = 400;
const ERROR_NOT_FOUND = 404;
const INTERNAL_CODE = 500;

module.exports = {
  DEV_SECRET,
  STATUS_OK,
  CREATED,
  INVAILD_ID,
  ERROR_NOT_FOUND,
  ERROR_CODE_UNIQUE,
  BAD_REQUEST_CODE,
  INTERNAL_CODE,
};
